import type { Patient } from '../types'

export const patients: Patient[] = [
  {
    id: 'p1',
    cardNumber: '02646',
    name: 'Keti',
    species: 'macka',
    breed: 'Kartuzijanska mačka',
    sex: 'zenka',
    age: 11,
    cardStatus: 'aktivan',
    allergies: 'nema',
    anamnesis: 'Redovna kontrola, dobro stanje.',
    ownerName: 'Stupar Dragan',
    phone: '064/3340181',
    address: 'Anastasa Jovanovića 15',
    city: 'Novi Sad',
    totalServicesRsd: 2300,
    paidRsd: 2300,
    visits: [
      {
        id: 'v1',
        type: 'Vakcinacija',
        date: '2015-12-11',
        title: 'Vakcinacija poli.',
        description: 'Polivalentna vakcina',
        costRsd: 1500,
      },
    ],
  },
  {
    id: 'p2',
    cardNumber: '04323',
    name: 'Lio',
    species: 'pas',
    breed: 'Bišon',
    sex: 'muzjak',
    age: 7,
    cardStatus: 'aktivan',
    allergies: 'polen',
    ownerName: 'Stupar Gordana',
    phone: '063/1805969',
    address: 'Janka Čmelika 75',
    city: 'Novi Sad',
    totalServicesRsd: 4200,
    paidRsd: 3000,
    visits: [],
  },
  {
    id: 'p3',
    cardNumber: '01804',
    name: 'Bela',
    species: 'pas',
    breed: 'Američki stafordski terijer',
    sex: 'zenka',
    age: 14,
    cardStatus: 'aktivan',
    allergies: 'hrana',
    ownerName: 'Subić Vladimir',
    phone: '060/7301103',
    address: 'Toplice Milana 20',
    city: 'Novi Sad',
    totalServicesRsd: 1800,
    paidRsd: 1800,
    visits: [],
  },
  {
    id: 'p4',
    cardNumber: '00498',
    name: 'Mita',
    species: 'pas',
    breed: 'Mops',
    sex: 'muzjak',
    age: 15,
    cardStatus: 'aktivan',
    allergies: 'buve_krpelji',
    ownerName: 'Subić i Snežana',
    phone: '021/553494',
    address: 'Stražilovska 31',
    city: 'Novi Sad',
    totalServicesRsd: 3600,
    paidRsd: 3600,
    visits: [],
  },
  {
    id: 'p5',
    cardNumber: '03311',
    name: 'Rex',
    species: 'pas',
    breed: 'Nemački ovčar',
    sex: 'muzjak',
    age: 5,
    cardStatus: 'aktivan',
    allergies: 'nema',
    ownerName: 'Jovanović Petar',
    phone: '065/2210044',
    address: 'Bulevar Oslobođenja 12',
    city: 'Beograd',
    totalServicesRsd: 5200,
    paidRsd: 5200,
    visits: [],
  },
  {
    id: 'p6',
    cardNumber: '02219',
    name: 'Luna',
    species: 'macka',
    breed: 'Domaća mačka',
    sex: 'zenka',
    age: 3,
    cardStatus: 'aktivan',
    allergies: 'lekovi',
    ownerName: 'Petrović Ana',
    phone: '062/8890021',
    address: 'Zmaj Jovina 4',
    city: 'Petrovaradin',
    totalServicesRsd: 900,
    paidRsd: 400,
    visits: [],
  },
  {
    id: 'p7',
    cardNumber: '01122',
    name: 'Coco',
    species: 'ptica',
    breed: 'Papagaj',
    sex: 'muzjak',
    age: 2,
    cardStatus: 'aktivan',
    allergies: 'ostalo',
    ownerName: 'Nikolić Milan',
    phone: '064/1123344',
    address: 'Narodnog fronta 8',
    city: 'Novi Sad',
    totalServicesRsd: 600,
    paidRsd: 600,
    visits: [],
  },
  {
    id: 'p8',
    cardNumber: '00877',
    name: 'Maza',
    species: 'pas',
    breed: 'Jazavičar',
    sex: 'zenka',
    age: 9,
    cardStatus: 'obrisan',
    allergies: 'nema',
    ownerName: 'Ilić Snežana',
    phone: '061/7765432',
    address: 'Kralja Petra 2',
    city: 'Beograd',
    totalServicesRsd: 1500,
    paidRsd: 1500,
    visits: [],
  },
]
