import type { Patient } from '../types'

export const patients: Patient[] = [
  {
    id: 'p1',
    cardNumber: '02646',
    name: 'Keti',
    species: 'cat',
    breed: 'Chartreux',
    sex: 'female',
    age: 11,
    cardStatus: 'active',
    allergies: 'none',
    anamnesis: 'Routine checkup, good condition.',
    ownerName: 'Stupar Dragan',
    phone: '064/3340181',
    address: 'Anastasa Jovanovića 15',
    city: 'Novi Sad',
    totalServicesRsd: 2300,
    paidRsd: 2300,
    visits: [
      {
        id: 'v1',
        type: 'Vaccination',
        date: '2015-12-11',
        title: 'Polyvalent vaccination',
        description: 'Polyvalent vaccine',
        costRsd: 1500,
      },
    ],
  },
  {
    id: 'p2',
    cardNumber: '04323',
    name: 'Lio',
    species: 'dog',
    breed: 'Bichon Frise',
    sex: 'male',
    age: 7,
    cardStatus: 'active',
    allergies: 'pollen',
    ownerName: 'Stupar Gordana',
    phone: '063/1805969',
    address: 'Janka Čmelika 75',
    city: 'Novi Sad',
    totalServicesRsd: 4200,
    paidRsd: 3000,
    visits: [],
  },
  {
    id: 'p3',
    cardNumber: '01804',
    name: 'Bela',
    species: 'dog',
    breed: 'American Staffordshire Terrier',
    sex: 'female',
    age: 14,
    cardStatus: 'active',
    allergies: 'food',
    ownerName: 'Subić Vladimir',
    phone: '060/7301103',
    address: 'Toplice Milana 20',
    city: 'Novi Sad',
    totalServicesRsd: 1800,
    paidRsd: 1800,
    visits: [],
  },
  {
    id: 'p4',
    cardNumber: '00498',
    name: 'Mita',
    species: 'dog',
    breed: 'Pug',
    sex: 'male',
    age: 15,
    cardStatus: 'active',
    allergies: 'fleas_ticks',
    ownerName: 'Subić i Snežana',
    phone: '021/553494',
    address: 'Stražilovska 31',
    city: 'Novi Sad',
    totalServicesRsd: 3600,
    paidRsd: 3600,
    visits: [],
  },
  {
    id: 'p5',
    cardNumber: '03311',
    name: 'Rex',
    species: 'dog',
    breed: 'German Shepherd',
    sex: 'male',
    age: 5,
    cardStatus: 'active',
    allergies: 'none',
    ownerName: 'Jovanović Petar',
    phone: '065/2210044',
    address: 'Bulevar Oslobođenja 12',
    city: 'Belgrade',
    totalServicesRsd: 5200,
    paidRsd: 5200,
    visits: [],
  },
  {
    id: 'p6',
    cardNumber: '02219',
    name: 'Luna',
    species: 'cat',
    breed: 'Domestic Shorthair',
    sex: 'female',
    age: 3,
    cardStatus: 'active',
    allergies: 'medication',
    ownerName: 'Petrović Ana',
    phone: '062/8890021',
    address: 'Zmaj Jovina 4',
    city: 'Petrovaradin',
    totalServicesRsd: 900,
    paidRsd: 400,
    visits: [],
  },
  {
    id: 'p7',
    cardNumber: '01122',
    name: 'Coco',
    species: 'bird',
    breed: 'Parrot',
    sex: 'male',
    age: 2,
    cardStatus: 'active',
    allergies: 'other',
    ownerName: 'Nikolić Milan',
    phone: '064/1123344',
    address: 'Narodnog fronta 8',
    city: 'Novi Sad',
    totalServicesRsd: 600,
    paidRsd: 600,
    visits: [],
  },
  {
    id: 'p8',
    cardNumber: '00877',
    name: 'Maza',
    species: 'dog',
    breed: 'Dachshund',
    sex: 'female',
    age: 9,
    cardStatus: 'deleted',
    allergies: 'none',
    ownerName: 'Ilić Snežana',
    phone: '061/7765432',
    address: 'Kralja Petra 2',
    city: 'Belgrade',
    totalServicesRsd: 1500,
    paidRsd: 1500,
    visits: [],
  },
]
