// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0161, CA1861, CA1814

namespace Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_Roles_OwnerLink_ClinicSchedule : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<int>(
                name: "role",
                schema: "public",
                table: "users",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<string>(
                name: "email",
                schema: "public",
                table: "owners",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "user_id",
                schema: "public",
                table: "owners",
                type: "uuid",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "clinic_schedules",
                schema: "public",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    day_of_week = table.Column<int>(type: "integer", nullable: false),
                    open_time = table.Column<TimeOnly>(type: "time without time zone", nullable: false),
                    close_time = table.Column<TimeOnly>(type: "time without time zone", nullable: false),
                    is_closed = table.Column<bool>(type: "boolean", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_clinic_schedules", x => x.id);
                });

            migrationBuilder.InsertData(
                schema: "public",
                table: "clinic_schedules",
                columns: new[] { "id", "close_time", "day_of_week", "is_closed", "open_time" },
                values: new object[,]
                {
                    { new Guid("a0000000-0000-0000-0000-000000000000"), new TimeOnly(20, 0, 0), 0, false, new TimeOnly(7, 0, 0) },
                    { new Guid("a0000000-0000-0000-0000-000000000001"), new TimeOnly(20, 0, 0), 1, false, new TimeOnly(7, 0, 0) },
                    { new Guid("a0000000-0000-0000-0000-000000000002"), new TimeOnly(20, 0, 0), 2, false, new TimeOnly(7, 0, 0) },
                    { new Guid("a0000000-0000-0000-0000-000000000003"), new TimeOnly(20, 0, 0), 3, false, new TimeOnly(7, 0, 0) },
                    { new Guid("a0000000-0000-0000-0000-000000000004"), new TimeOnly(20, 0, 0), 4, false, new TimeOnly(7, 0, 0) },
                    { new Guid("a0000000-0000-0000-0000-000000000005"), new TimeOnly(20, 0, 0), 5, false, new TimeOnly(7, 0, 0) },
                    { new Guid("a0000000-0000-0000-0000-000000000006"), new TimeOnly(20, 0, 0), 6, false, new TimeOnly(7, 0, 0) }
                });

            migrationBuilder.CreateIndex(
                name: "ix_owners_email",
                schema: "public",
                table: "owners",
                column: "email",
                unique: true,
                filter: "\"email\" IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ix_owners_user_id",
                schema: "public",
                table: "owners",
                column: "user_id",
                unique: true,
                filter: "\"user_id\" IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "ix_clinic_schedules_day_of_week",
                schema: "public",
                table: "clinic_schedules",
                column: "day_of_week",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "fk_owners_users_user_id",
                schema: "public",
                table: "owners",
                column: "user_id",
                principalSchema: "public",
                principalTable: "users",
                principalColumn: "id",
                onDelete: ReferentialAction.SetNull);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_owners_users_user_id",
                schema: "public",
                table: "owners");

            migrationBuilder.DropTable(
                name: "clinic_schedules",
                schema: "public");

            migrationBuilder.DropIndex(
                name: "ix_owners_email",
                schema: "public",
                table: "owners");

            migrationBuilder.DropIndex(
                name: "ix_owners_user_id",
                schema: "public",
                table: "owners");

            migrationBuilder.DropColumn(
                name: "role",
                schema: "public",
                table: "users");

            migrationBuilder.DropColumn(
                name: "email",
                schema: "public",
                table: "owners");

            migrationBuilder.DropColumn(
                name: "user_id",
                schema: "public",
                table: "owners");
        }
    }
}
