// <auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0161, CA1861

namespace Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_Trigram_Search_Indexes : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AlterDatabase()
                .Annotation("Npgsql:PostgresExtension:pg_trgm", ",,");

            migrationBuilder.CreateIndex(
                name: "ix_patients_anamnesis",
                schema: "public",
                table: "patients",
                column: "anamnesis")
                .Annotation("Npgsql:IndexMethod", "gin")
                .Annotation("Npgsql:IndexOperators", new[] { "gin_trgm_ops" });

            migrationBuilder.CreateIndex(
                name: "ix_patients_chip_number",
                schema: "public",
                table: "patients",
                column: "chip_number")
                .Annotation("Npgsql:IndexMethod", "gin")
                .Annotation("Npgsql:IndexOperators", new[] { "gin_trgm_ops" });

            migrationBuilder.CreateIndex(
                name: "ix_patients_name",
                schema: "public",
                table: "patients",
                column: "name")
                .Annotation("Npgsql:IndexMethod", "gin")
                .Annotation("Npgsql:IndexOperators", new[] { "gin_trgm_ops" });

            migrationBuilder.CreateIndex(
                name: "ix_owners_address",
                schema: "public",
                table: "owners",
                column: "address")
                .Annotation("Npgsql:IndexMethod", "gin")
                .Annotation("Npgsql:IndexOperators", new[] { "gin_trgm_ops" });

            migrationBuilder.CreateIndex(
                name: "ix_owners_first_name",
                schema: "public",
                table: "owners",
                column: "first_name")
                .Annotation("Npgsql:IndexMethod", "gin")
                .Annotation("Npgsql:IndexOperators", new[] { "gin_trgm_ops" });

            migrationBuilder.CreateIndex(
                name: "ix_owners_last_name",
                schema: "public",
                table: "owners",
                column: "last_name")
                .Annotation("Npgsql:IndexMethod", "gin")
                .Annotation("Npgsql:IndexOperators", new[] { "gin_trgm_ops" });

            migrationBuilder.CreateIndex(
                name: "ix_owners_phone_number",
                schema: "public",
                table: "owners",
                column: "phone_number")
                .Annotation("Npgsql:IndexMethod", "gin")
                .Annotation("Npgsql:IndexOperators", new[] { "gin_trgm_ops" });

            migrationBuilder.CreateIndex(
                name: "ix_breeds_name",
                schema: "public",
                table: "breeds",
                column: "name")
                .Annotation("Npgsql:IndexMethod", "gin")
                .Annotation("Npgsql:IndexOperators", new[] { "gin_trgm_ops" });

            migrationBuilder.CreateIndex(
                name: "ix_allergens_name",
                schema: "public",
                table: "allergens",
                column: "name")
                .Annotation("Npgsql:IndexMethod", "gin")
                .Annotation("Npgsql:IndexOperators", new[] { "gin_trgm_ops" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "ix_patients_anamnesis",
                schema: "public",
                table: "patients");

            migrationBuilder.DropIndex(
                name: "ix_patients_chip_number",
                schema: "public",
                table: "patients");

            migrationBuilder.DropIndex(
                name: "ix_patients_name",
                schema: "public",
                table: "patients");

            migrationBuilder.DropIndex(
                name: "ix_owners_address",
                schema: "public",
                table: "owners");

            migrationBuilder.DropIndex(
                name: "ix_owners_first_name",
                schema: "public",
                table: "owners");

            migrationBuilder.DropIndex(
                name: "ix_owners_last_name",
                schema: "public",
                table: "owners");

            migrationBuilder.DropIndex(
                name: "ix_owners_phone_number",
                schema: "public",
                table: "owners");

            migrationBuilder.DropIndex(
                name: "ix_breeds_name",
                schema: "public",
                table: "breeds");

            migrationBuilder.DropIndex(
                name: "ix_allergens_name",
                schema: "public",
                table: "allergens");

            migrationBuilder.AlterDatabase()
                .OldAnnotation("Npgsql:PostgresExtension:pg_trgm", ",,");
        }
    }
}
