// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0161, CA1861

namespace Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_Appointment_Lifecycle : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<DateTime>(
                name: "checked_in_at",
                schema: "public",
                table: "appointments",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<DateTime>(
                name: "closed_at",
                schema: "public",
                table: "appointments",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.AddColumn<Guid>(
                name: "closed_by_user_id",
                schema: "public",
                table: "appointments",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "resolution_note",
                schema: "public",
                table: "appointments",
                type: "text",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "ix_appointments_closed_by_user_id",
                schema: "public",
                table: "appointments",
                column: "closed_by_user_id");

            migrationBuilder.CreateIndex(
                name: "ix_appointments_status_starts_at",
                schema: "public",
                table: "appointments",
                columns: new[] { "status", "starts_at" });

            migrationBuilder.AddForeignKey(
                name: "fk_appointments_users_closed_by_user_id",
                schema: "public",
                table: "appointments",
                column: "closed_by_user_id",
                principalSchema: "public",
                principalTable: "users",
                principalColumn: "id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_appointments_users_closed_by_user_id",
                schema: "public",
                table: "appointments");

            migrationBuilder.DropIndex(
                name: "ix_appointments_closed_by_user_id",
                schema: "public",
                table: "appointments");

            migrationBuilder.DropIndex(
                name: "ix_appointments_status_starts_at",
                schema: "public",
                table: "appointments");

            migrationBuilder.DropColumn(
                name: "checked_in_at",
                schema: "public",
                table: "appointments");

            migrationBuilder.DropColumn(
                name: "closed_at",
                schema: "public",
                table: "appointments");

            migrationBuilder.DropColumn(
                name: "closed_by_user_id",
                schema: "public",
                table: "appointments");

            migrationBuilder.DropColumn(
                name: "resolution_note",
                schema: "public",
                table: "appointments");
        }
    }
}
