// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
#pragma warning disable IDE0161, CA1861

namespace Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_Appointments : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "appointments",
                schema: "public",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    created_by_user_id = table.Column<Guid>(type: "uuid", nullable: false),
                    owner_id = table.Column<Guid>(type: "uuid", nullable: true),
                    patient_id = table.Column<Guid>(type: "uuid", nullable: true),
                    starts_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    duration_minutes = table.Column<int>(type: "integer", nullable: false),
                    ends_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false),
                    type = table.Column<int>(type: "integer", nullable: false),
                    status = table.Column<int>(type: "integer", nullable: false),
                    reason = table.Column<string>(type: "text", nullable: true),
                    created_at = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_appointments", x => x.id);
                    table.ForeignKey(
                        name: "fk_appointments_owners_owner_id",
                        column: x => x.owner_id,
                        principalSchema: "public",
                        principalTable: "owners",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_appointments_patients_patient_id",
                        column: x => x.patient_id,
                        principalSchema: "public",
                        principalTable: "patients",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "fk_appointments_users_created_by_user_id",
                        column: x => x.created_by_user_id,
                        principalSchema: "public",
                        principalTable: "users",
                        principalColumn: "id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "ix_appointments_created_by_user_id",
                schema: "public",
                table: "appointments",
                column: "created_by_user_id");

            migrationBuilder.CreateIndex(
                name: "ix_appointments_owner_id",
                schema: "public",
                table: "appointments",
                column: "owner_id");

            migrationBuilder.CreateIndex(
                name: "ix_appointments_patient_id",
                schema: "public",
                table: "appointments",
                column: "patient_id");

            migrationBuilder.CreateIndex(
                name: "ix_appointments_starts_at",
                schema: "public",
                table: "appointments",
                column: "starts_at");

            // One appointment per slot: no two active bookings (Scheduled = 0, CheckedIn = 1)
            // may cover overlapping time. A partial GiST range-exclusion constraint — the only
            // thing that holds under two concurrent inserts racing for the same slot. Half-open
            // '[)' so 09:00-09:30 and 09:30-10:00 do not count as overlapping. No btree_gist
            // extension needed: the constraint uses only a range && operator, which GiST
            // supports natively. Cancelled / NoShow / Completed rows fall out of the filter and
            // release their time for rebooking.
            migrationBuilder.Sql(
                @"ALTER TABLE public.appointments
                  ADD CONSTRAINT ck_appointments_no_overlap
                  EXCLUDE USING gist (tstzrange(starts_at, ends_at, '[)') WITH &&)
                  WHERE (status IN (0, 1));");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE public.appointments DROP CONSTRAINT IF EXISTS ck_appointments_no_overlap;");

            migrationBuilder.DropTable(
                name: "appointments",
                schema: "public");
        }
    }
}
